-- AI Optimization (NAI section - only affects AI)
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_DOCTRINE = 10000
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_TEMPLATE = 10000
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_EQUIPMENT = 10000
NDefines.NAI.HOURS_BETWEEN_ENCIRCLEMENT_DISCOVERY = 24
NDefines.NAI.AI_UPDATE_ROLES_FREQUENCY_HOURS = 60000000
NDefines.NAI.UPDATE_SUPPLY_MOTORIZATION_FREQUENCY_HOURS = 60000000
NDefines.NAI.UPDATE_SUPPLY_BOTTLENECKS_FREQUENCY_HOURS = 336000
NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 60
NDefines.NAI.MICRO_POCKET_SIZE = 0
NDefines.NAI.DAYS_BETWEEN_AIR_PRIORITIES_UPDATE = 20000
NDefines.NAI.DIPLOMACY_RECALCULATE_INTERVAL = 2000
NDefines.NAI.PLAN_ACTIVATION_SUPERIORITY_AGGRO = 2.0
