NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 90
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 365
NDefines.NGame.GAME_SPEED_SECONDS = { 1.0, 0.35, 0.25, 0.1, 0.0 }
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 3
NDefines.NGame.MESSAGE_TIMEOUT_DAYS = 10
NDefines.NGame.EVENT_TIMEOUT_DEFAULT = 7

NDefines.NDiplomacy.TROOP_FEAR = 0.25
NDefines.NDiplomacy.FLEET_FEAR = 0.25
NDefines.NDiplomacy.EMBARGO_COST = 50
NDefines.NDiplomacy.EMBARGO_THREAT_THRESHOLD = -1
NDefines.NDiplomacy.EVENT_PROCESS_OFFSET = 30
NDefines.NDiplomacy.IDEOLOGY_JOIN_FACTION_MIN_LEVEL = 0.0

NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 24
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 18
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 5
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 2500
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 2500
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 2500

NDefines.NAI.HOUR_BAD_COMBAT_REEVALUATE = 96
NDefines.NAI.RESEARCH_DAYS_BETWEEN_WEIGHT_UPDATE = 60
NDefines.NAI.PRODUCTION_MAX_PROGRESS_TO_SWITCH_NAVAL = 0.35
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_DOCTRINE = 360    
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_TEMPLATE = 360
NDefines.NAI.DAYS_BETWEEN_CHECK_BEST_EQUIPMENT = 360
NDefines.NAI.EQUIPMENT_MARKET_UPDATE_FREQUENCY_DAYS = 28
NDefines.NAI.DAYS_BETWEEN_AIR_PRIORITIES_UPDATE = 28
NDefines.NAI.UPGRADES_DEFICIT_LIMIT_DAYS = 3
NDefines.NAI.NAVAL_INVADED_AREA_PRIO_DURATION = 30
NDefines.NAI.FAILED_INVASION_AVOID_DURATION = 90
NDefines.NAI.AI_UPDATE_ROLES_FREQUENCY_HOURS = 96
NDefines.NAI.UPDATE_SUPPLY_BOTTLENECKS_FREQUENCY_HOURS = 168
NDefines.NAI.AI_PREFERRED_TACTIC_WEEKLY_CHANGE_CHANCE = 0.02

NDefines.NCountry.BASE_MAX_COMMAND_POWER = 500.0
NDefines.NCountry.BASE_COMMAND_POWER_GAIN = 0.5
NDefines.NCountry.NUM_DAYS_TO_FULLY_DELETE_STOCKPILED_EQUIPMENT = 45
NDefines.NCountry.POPULATION_YEARLY_GROWTH_BASE = 0.01
NDefines.NCountry.POLITICAL_POWER_UPPER_CAP = 5000.0

NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 15
NDefines.NProduction.FLOATING_HARBOR_MAX_NAV_FACTORIES_PER_LINE = 15
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 15
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 15

NDefines.NTrade.BASE_LAND_TRADE_RANGE = 2000
NDefines.NTrade.DISTANCE_TRADE_FACTOR = -0.05

NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 60

NDefines.NMarket.MAX_CIV_FACTORIES_PER_CONTRACT = 15
NDefines.NMarket.WARNING_CONVOYS_SUNK_MAX_DAYS  = 15

NDefines.NIndustrialOrganisation.ASSIGN_DESIGN_TEAM_PP_COST_PER_DAY = 0.05

NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 2.75